### ISSUE TITLE
API is not active

### ISSUE THREAD

**Issue by xajist** [ariaramin/RadioAva#1]
where do I find this API ?

String BASE_URL = "https://radiojavan.pythonanywhere.com/";

**Comment by ariaramin** [comment]
> where do I find this API ?
> 
> String BASE_URL = "https://radiojavan.pythonanywhere.com/";

I used a free hosting service for this project, which comes with limitations. Unfortunately, after 3 months of deployment, the hosting was disabled. I have extended its duration, but note that it will be disabled again after 3 months
